/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stand.up.timer.desktop.v1;

import javax.swing.SwingUtilities;

/**
 *
 * @author iaketepe
 */
public class HomePanel extends javax.swing.JPanel implements TimerDisplay {

    public StandUpTimer timer;
    private final CardSwitch cSwitch;
    /**
     * Creates new form HomePanel
     */
    public HomePanel(CardSwitch cs) {
        initComponents();
        this.timer = new StandUpTimer(this);
        this.cSwitch = cs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stop = new javax.swing.JButton();
        start = new javax.swing.JButton();
        loop = new javax.swing.JToggleButton();
        settings = new javax.swing.JButton();
        timerVal = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 190, -1, -1));

        loop.setText("Loop");
        loop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopActionPerformed(evt);
            }
        });
        add(loop, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 254, -1, -1));

        settings.setText("Settings");
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 6, -1, -1));

        timerVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerVal.setText("Timer Time");
        add(timerVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 121, 136, 31));

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("Stand Up Timer");
        idLabel.setVerifyInputWhenFocusTarget(false);
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 87, 97, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        timer.stopTimer();
    }//GEN-LAST:event_stopActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        timer.startTimer();
    }//GEN-LAST:event_startActionPerformed

    private void loopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopActionPerformed
        timer.loopTimer();
    }//GEN-LAST:event_loopActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        cSwitch.showPanel("settings");
    }//GEN-LAST:event_settingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idLabel;
    private javax.swing.JToggleButton loop;
    private javax.swing.JButton settings;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    private javax.swing.JLabel timerVal;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void updateDisplayVal(String text) {
        SwingUtilities.invokeLater(() -> timerVal.setText(text));
    }

    @Override
    public void updateDisplayLabel(String text) {
        SwingUtilities.invokeLater(() -> idLabel.setText(text));
    }
}
