/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stand.up.timer.desktop.v1;

/**
 *
 * @author iaketepe
 */
public class SettingsPanel extends javax.swing.JPanel {

    private CardSwitch cSwitch;
    private StandUpTimer timer;
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel(CardSwitch cs, StandUpTimer timer) {
        initComponents();
        this.cSwitch = cs;
        this.timer = timer;
        volumeSlider.addChangeListener(e -> {
            int value = volumeSlider.getValue();
            this.timer.changeVolume(value);
            volumeLabel.setText("Volume: " + value + "%");
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        volumeSlider = new javax.swing.JSlider();
        volumeLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Back");
        back.setVerifyInputWhenFocusTarget(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 6, 77, 32));
        add(volumeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, -1, -1));

        volumeLabel.setText("Volume: 50%");
        add(volumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("Settings");
        idLabel.setVerifyInputWhenFocusTarget(false);
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 87, 97, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        cSwitch.showPanel("home");
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
