/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stand.up.timer.desktop.v1;
//import java.util.Timer;
import java.awt.AWTException;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class StandUpJFrame extends javax.swing.JFrame implements CardSwitch {
    
    private CardLayout cardLayout;
    private JPanel cards;
    private HomePanel homePanel;
    private SettingsPanel settingsPanel;
    /**
     * Creates new form StandUpJFrame
     */
    
    public StandUpJFrame() {
        //initComponents();
        homePanel = new HomePanel(this);
        settingsPanel = new SettingsPanel(this, homePanel.timer);
        
        cardLayout = new CardLayout();
        cards = new JPanel(cardLayout);
        
        cards.add(homePanel, "home");
        cards.add(settingsPanel, "settings");
        setTitle("Stand Up Timer");
        getContentPane().removeAll();
        getContentPane().setPreferredSize(new Dimension(400,300));
        getContentPane().add(cards);
        pack();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        
        cardLayout.show(cards, "home");
        
        setupSystemTray();
        
    }
    
    
   private void setupSystemTray() {
        if (!SystemTray.isSupported()) return;

        SystemTray tray = SystemTray.getSystemTray();
        //Image image = Toolkit.getDefaultToolkit().getImage("icon.png");
        PopupMenu popup = new PopupMenu();
        MenuItem openItem = new MenuItem("Open");
        MenuItem exitItem = new MenuItem("Exit");
        popup.add(openItem);
        popup.add(exitItem);

        //Image trayImage = new Image("icon.png"); //new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB); 
        Image trayImage = Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png"));
        TrayIcon trayIcon = new TrayIcon(trayImage, "Stand Up Timer", popup);
        trayIcon.setImageAutoSize(true);

        // Restore window on tray icon click
        trayIcon.addActionListener(e -> {
            this.setVisible(true);
            this.setExtendedState(NORMAL);
            tray.remove(trayIcon);
        });

        // Open menu item
        openItem.addActionListener(e -> {
            this.setVisible(true);
            this.setExtendedState(NORMAL);
            tray.remove(trayIcon);
        });

        // Exit menu item
        exitItem.addActionListener(e -> {
            tray.remove(trayIcon);
            System.exit(0);
        });

        // Minimize to tray
        this.addWindowStateListener(e -> {
            if (e.getNewState() == ICONIFIED) {
                try {
                    tray.add(trayIcon);
                    this.setVisible(false);
                } catch (AWTException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StandUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StandUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StandUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StandUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StandUpJFrame().setVisible(true);
            }
        });
    }

    @Override
    public void showPanel(String panelName) {
        cardLayout.show(cards, panelName);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
